### ISSUE TITLE
Changing mission settings via 3DEN.

### ISSUE THREAD

**Issue by Andrees97** [genesis92x/VcomAI-3.0#1]
It would be nice to add the possibility to change the mission specific settings via the 3DEN Editor CBA Menu before compiling and starting the mission and not just after it has already started (the way it is now). 
I know there was a 3DEN extension for 2.94 somewhere, I used it.
Thanks!

(this should be in the mod version)

**Comment by Freddo3000** [comment]
Resolved in addon version.
