### ISSUE TITLE
VCM_SKILLCHANGE=false has no effect

### ISSUE THREAD

**Issue by Lothear** [genesis92x/VcomAI-3.0#10]
Hi Genesis,
Changing VCM_SKILLCHANGE to false in the userconfig folder and/or in the in-game menu has no effect. 
The same goes for adding VCM_SKILLCHANGE = false at the end of the init. 
Script and mod version alike. 
Tested with and without mods (file patching enabled), no change whatsover.
Thanks.

**Comment by genesis92x** [comment]
Thanks for the report, I will look into it.
