### ISSUE TITLE
FFE config error in 3.3.0

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#101]
**Describe the bug**
When entering a server or hosting a mission on client with VCOM, this always occour.
I remember somewhere said that FFE config error was fixed, are you sure that fix takes effects?

**To Reproduce**
1. Entering a server or host a mission with VCOM 3.3.0 on.
**Expected behavior**
I'm not sure.

**Screenshots**
Unable to upload screenshots to Github in China recently, so a third-party link is provided below:
https://www.z4a.net/images/2019/03/31/107410_20190331152921_1.jpg

**VCOM Version:**
 - Branch: [Master - Latest Steam Workshop Release]
 - Version [e.g. 3.3.0]
 
**Additional mods used:**
 - CBA_A3 (v3.10.1.190316)

**Comment by Freddo3000** [comment]
What vehicle was this tested with? It seems like it might be a config issue.

**Comment by Freddo3000** [comment]
Actually, nevermind. It is expecting a string, when in it is in reality a array. Probably something introduced with UXO.

**Comment by GoldJohnKing** [comment]
I just enter my mission then the error shows up, so I'm not sure about what vehicles.

And do you mean this error is normal and no need to fix?
