### ISSUE TITLE
AI Cohesion is off - do not engage enemies consistently

### ISSUE THREAD

**Issue by genesis92x** [genesis92x/VcomAI-3.0#104]
**Describe the bug**
AI groups will scatter all over the place in combat, running back and forth repeatedly. This is especially prevalent when AI squads are constantly respawning into a group already in combat.

**To Reproduce**
1. Have a large group of AI engage in combat
2. Give them waypoints or wait for waypoints to be generated
3. Watch AI scatter in multiple directions/not engage AI that are directly in LOS

**Expected behavior**
AI should be more cohesive and  responsive during combat. Currently feels like  they are slow to respond.

**VCOM Version:**
Develop Branch

**Additional mods used:**
Vanilla

-I believe this is due to the new suppression system and the controlling of the combat modes.
-After months of testing I found it best to NOT touch combat modes/ai targeting/using disableAI in the MAJORITY of situations. There are always exceptions.

I will disable some features here and there to see if AI become more responsive. Should also help FPS.

Simple is often better when it comes to ArmA

**Comment by GoldJohnKing** [comment]
Hi, I'd like to know if develop branch is ready to be pre-released. If there's no major bug, I could testing it on my public server with around 30 players then probably provide feedbacks, and I'd like to provide a long-term testing environment on my server.

**Comment by aussie-battler** [comment]
Ill second that, would love to change ai response. Maybe when one gets killed the group they all get into REd combat mode. 	

_unit setCombatMode "RED";

**Comment by genesis92x** [comment]
@GoldJohnKing I appreciate the support. It really does save so much time to have others doing the testing (Understandably it can be irritating for the community). I'm not sure the development branch is ready for another round of testing. I have some changes that I really would like to focus on this week. I have several hours of free time on Sunday 4/7/19, later in the evening, that I plan to work on Vcom. I will push an update to the develop branch then. 

The develop branch will be going through some changes, so expect bugs. I don't wish to undo the massive amount of work that went into the new systems, they just need some tweaking here and there. 

Maybe @Freddo3000 can speak more to this, but the first test I'd like to see is if we can simply modify the original AI behavior instead of trying to overhaul it. Making it more fluid hopefully.
