### ISSUE TITLE
[Question]VCM_DLIMIT param error possible related to AISettingsV5.hpp

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#107]
**Describe the bug**
When a server load a mission with vcom, this error shows up.
I'm sure I have the correct AISettingsV5.hpp configuration, so it may be a script error.

**Screenshot**
![107410_20190404113658_1](https://user-images.githubusercontent.com/26923626/55528678-45751c80-56d0-11e9-9924-0d54cf405740.png)

**VCOM Version:**
 - Branch: [Develop]
 - Version [3.3.0 - 9504c27]

**Comment by Freddo3000** [comment]
Can't replicate on my machine. What is your AISettingsV5 configure to?

**Comment by GoldJohnKing** [comment]
Please See:
https://gist.github.com/GoldJohnKing/1d8e0c0efebd08052319d3794b598d2c

Also, here's the description.ext file:
https://gist.github.com/GoldJohnKing/e893aa0ae880c6d462d578da37d052e2

**Comment by GoldJohnKing** [comment]
Nope, it is not fixed. Here's the related rpt contents. The Chinese character in it means "Undefined Variable in Expression"

```
23:02:33 Error in expression <List = [];
{

if ((count _driverList) > VCM_DLIMIT) then {_driverList breakOut ">
23:02:33   Error position: <VCM_DLIMIT) then {_driverList breakOut ">
23:02:33   Error 表达式中未定义的变量：vcm_dlimit
23:02:33 File Vcom\Functions\VCM_Functions\driving\fn_UpdateDrivers.sqf [VCM_fnc_UpdateDrivers], line 21
```

Full rpt is here, if needed.
[Arma3_x64_2019-04-04_22-53-19.zip](https://github.com/genesis92x/VcomAI-3.0/files/3044160/Arma3_x64_2019-04-04_22-53-19.zip)

**Comment by Freddo3000** [comment]
Double check that filepatching is enabled on whoever is the server, and that the AISettingsV5 file is where it is supposed to be. Also, your description.ext is out of date.

**Comment by GoldJohnKing** [comment]
Sorry, it was a outdated description.
