### ISSUE TITLE
Mount / Dismount - cycling bug

### ISSUE THREAD

**Issue by Dunkelzahn86** [genesis92x/VcomAI-3.0#11]
Using transport vehicles with squads causes the squad leader to repeatedly give the mount / dismount - orders. Seems to be effected by the 'steal vehicle' - option. I will personally run a few tests today on this, with just CBA and VCOM.

**Comment by Dunkelzahn86** [comment]
Did some quick testing. Troops act normal until combat. When combat starts, the squad leader of a mech / motor squad starts spamming mount, until every unit of the squad has entered the vehicle. The leader then tells the squad to dismount and the vehicle usually moves a short distance, after which the mount/dismount loop repeats. Toggling steal vehicle in options didn't seem to have any effect on this.

**Comment by Freddo3000** [comment]
This bug appears to happen in vanilla aswell.

Suggested fix: Create an "unload" waypoint when entering combat, and a "load" waypoint once exiting combat.

**Comment by genesis92x** [comment]
This behavior is very frustrating - I would like to find a way to force the AI to just remain in the vehicle until combat.

**Comment by xetra11** [comment]
Would be great if VCOM could fix this issue (even tho it may be vanilla) !

**Comment by Freddo3000** [comment]
> 
> 
> Would be great if VCOM could fix this issue (even tho it may be vanilla) !

It is a vanilla issue, and it is very hard to fix as unless you make the AI literally braindead they'll want to get out.

**Comment by GoldJohnKing** [comment]
After 3.2.2 release, AI has a much more lower rate to have Mount / Dismount - cycling bug with vanilla driving, but it still presents while enabling VCOM Driving feature. Besides, VCOM Driving seems paying no attention to infantry, as it has a much more higher rate to roll over infantries, including civilians. (The driver seems crazy and the scene looks bloody...)

**Comment by Freddo3000** [comment]
VCOM Driving has no effect on dismount/get in behaviour. It is entirely separate from that.

There's currently a significant improvement to `boundingBoxReal` on dev branch, that will allows us to make significant upgrades to VCOM Driving, until then I'd suggest turning it off if it is causing issues. After all, it is marked as experimental.
