### ISSUE TITLE
[Testing Result] Current develop branch testing result.

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#110]
I've merged current develop branch into master branch on my forked repository (https://github.com/GoldJohnKing/VcomAI-3.0/commit/c2d19f0f5ca6605430aaedc50e4fd5e8e544b04d), then run the script on my public server with 30 players for more than 15 hours.

**No major errors are shown or logged, despite the following "possible" issues:**

1. FFE seems not functional, though Artillery Targets are generated. I'm not sure if it's because no enemy arty units are spawned by the mission.

2. Several players has reported that they still see "frozen" AI Groups having no reaction when being attacked or no response to any combat, but too much less than before, and they said it's acceptable.

3. Many players has reported that enemy jet will try to land on airport when they are in safe mode, instead of flying around, I'm not sure if this is a vanilla behavior or impacted by VCOM.

4. AI still seems to have "Mount / Dismount" cycle on transport vehicles, but much less than before, and the circumstances seems to be better: now they only have this cycle when they sopt enemies then lose eye contact with spotted enemies and spot the enemy again, and after a few cycle, they will all dismount for compact or all mounted and continue to move. Related issue: https://github.com/genesis92x/VcomAI-3.0/issues/11 .

**Other minor issues still not fixed or handled:**
https://github.com/genesis92x/VcomAI-3.0/issues/106
https://github.com/genesis92x/VcomAI-3.0/issues/108
https://github.com/genesis92x/VcomAI-3.0/issues/109 .

**Sure to be already fixed issues in current develop branch:**
https://github.com/genesis92x/VcomAI-3.0/issues/93
https://github.com/genesis92x/VcomAI-3.0/issues/94
https://github.com/genesis92x/VcomAI-3.0/issues/96
https://github.com/genesis92x/VcomAI-3.0/issues/98
https://github.com/genesis92x/VcomAI-3.0/issues/99
https://github.com/genesis92x/VcomAI-3.0/issues/100
https://github.com/genesis92x/VcomAI-3.0/issues/101
https://github.com/genesis92x/VcomAI-3.0/issues/105

**Unable to reproduce:**
https://github.com/genesis92x/VcomAI-3.0/issues/102

**Invalid issue:**
https://github.com/genesis92x/VcomAI-3.0/issues/81 - Reason: The logic for placing mines and demo blocks is separate. See: https://github.com/genesis92x/VcomAI-3.0/issues/93#issuecomment-477125046

So, I bet current develop branch could be a stable release. The CQC function seems great lol, and the steal vehicle based on units' class works well, too. Thanks for your efforts and can't wait to see your new stable release!

**Comment by TBartels1** [comment]
#102 seems to occur when there is artillery and/or tanks present. I did a test with IFA3 infantry, artillery and tanks present. I also tested with infantry and artillery exclusively, same for tanks. The error messages will appear after some time whenever artillery or tanks are present. However, there will be no error messages when only infantry is present.

**Comment by GoldJohnKing** [comment]
I could not reproduce this error with RHSAFRF as enemy units and RHSUSAF as friendly units, though there are both enemy-side tanks spawned in-mission and friendly-side driven by players. It might be a IFA3 compatibility issue?

**Comment by TBartels1** [comment]
Hmm yeah that could be! I attached the testmission I've tested with in the editor. This one also has some FOW infantry in it. Only required mods should be IFA3 AIO and FOW. After a certain amount of time the error messages should show up. 

[VCom%20Test%20without%20CSA38.Colleville.zip](https://github.com/genesis92x/VcomAI-3.0/files/3063754/VCom.20Test.20without.20CSA38.Colleville.zip)
