### ISSUE TITLE
CQC mode cause huge performance loss.

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#114]
**Describe the bug**
When using current develop branch, our server encounter huge performance loss on AI units going into CQC mode. I'm pretty sure that it is caused by CQC. I've run plenty test, not just because CQC is the only new function added in 3.3.0 version. The performance loss only happens when CQC mode is on (hinted by systemchat).
AI in CQC mode also generates huge amounts of waypoints that they will never execute. This happens especially when AIs are on a static weapon or a vehicle. Then the static weapon or the vehicle will freeze and crazyingly generate waypoints and keep freezing, causing more and more useless waypoints.

**Expected behavior**
I suggest to add a function to disable CQC mode and mark it as an experimental feature.

**Screenshots**
![107410_20190413201105_1](https://user-images.githubusercontent.com/26923626/56089070-94d0ff00-5ebf-11e9-88c0-05daeaa477da.png)

**VCOM Version:**
I use 3.2.1 to compare with 3.3.0 and current develop branch, only 3.3.0 and current develop branch have encountered huge performance loss in city areas.

**Comment by genesis92x** [comment]
Issue resolved - CQC function removed
