### ISSUE TITLE
bugges i have come across when useing 3.3.0 (script mode)

### ISSUE THREAD

**Issue by davidp234** [genesis92x/VcomAI-3.0#116]
**Describe the bug**
after installing the script to my mission file i get the errors listed below

**Expected behavior**
to work as intended haha

**VCOM Version:**
3.3.0 script

**Additional mods used:**
-mod@Exile;@CUP_Terrains_Core;@CUP_Terrains_Maps;@Esseker;@CBA_A3;@CUP_Units;@CUP_Weapons;@CUP_Vehicles;@task_force_radio;@Immersion Cigs;@KA Weapons Pack NEW;@TRYK;@Zombies and Demons;@NIArms All in One;@Extended_Base_Mod; -servermod @exileserver

**Additional context**
if (VCM_AI_VEH_CLASS_STEAL) then
{
 
 
{
 
 
pri>
22:13:40   Error position: <VCM_AI_VEH_CLASS_STEAL) then
{
 
 
{
 
 
pri>
22:13:40   Error Undefined variable in expression: vcm_ai_veh_class_steal
22:13:40 File Vcom\Functions\VCM_Functions\fn_vehiclecommandeer.sqf [VCM_fnc_vehiclecommandeer], line 26
22:13:45 Error in expression <lots = [];
private _Crewmen = [];
21:45:26   Error position: <sleep 1.25;
};>
21:45:26   Error Generic error in expression
21:45:26 File \vcomai\Vcom\Functions\VCM_Functions\explosives\fn_MineMonitor.sqf [VCM_fnc_MineMonitor], line 56
21:45:26 Suspending not allowed in this context
21:45:26 Error in expression < isEqualTo _x;});
} foreach _RemoveLst;
sleep 1.25;
};>

if (VCM_AI_VEH_CLASS_STEAL) then
{
 
 
{
 
 
pri>
22:21:12   Error position: <VCM_AI_VEH_CLASS_STEAL) then
{
 
 
{
 
 
pri>
22:21:12   Error Undefined variable in expression: vcm_ai_veh_class_steal
22:21:12 File Vcom\Functions\VCM_Functions\fn_vehiclecommandeer.sqf [VCM_fnc_vehiclecommandeer], line 26

if !(VCM_MEDICALACTIVE) exitWith {};
 
params >
22:04:04   Error position: <VCM_MEDICALACTIVE) exitWith {};
 
params >
22:04:04   Error Undefined variable in expression: vcm_medicalactive
22:04:04 File Vcom\Functions\VCM_Functions\fn_MedicalHandler.sqf [VCM_fnc_MedicalHandler], line 14

**Comment by genesis92x** [comment]
Can you try the "develop" code from GitHub and see if these errors continue?

Make sure to delete the old Vcom AI folders
