### ISSUE TITLE
"Error Undefined variable in expression: _buildinglocation" in current develop branch

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#117]
**Describe the bug**
When checking recent rpt file, I found this:
```
19:48:05   Error Undefined variable in expression: _buildinglocation
19:48:05 File Vcom\Functions\VCM_Functions\fn_GarrisonLight.sqf [VCM_fnc_GarrisonLight], line 35
19:48:05 Error in expression <cation = selectRandom _tempA;
_x doMove _buildingLocation;
[_x,_buildingLocation>
```

**To Reproduce**
Run a public server, have some players and AIs hunting each other at a dense city for a while, and this error will show up in rpt file.

**Expected behavior**

**Screenshots**

**VCOM Version:**
 - Branch: [Current Develop Branch]
 - Version [commit 703e4d8]

**Comment by genesis92x** [comment]
Nice find - updated the develop branch - hopefully that bug is now gone.
