### ISSUE TITLE
"Userconfig/VCOMai/aisettingsv4.hpp not found"

### ISSUE THREAD

**Issue by ghost** [genesis92x/VcomAI-3.0#118]
**Describe the bug**
On editor mode VCOM ai pulls this fat error on the screen:
"Script userconfig/VCOMai/aisettingsv4.hpp not found"

I am running the main workshop version.

**To Reproduce**
1. Go on any singleplayer editor and run the game with an ai.
2. The error should appear.

**Expected behavior**
YOu'd think VCOM needs the config to do anything right?

**Screenshots**

**VCOM Version:**
 - Branch: [e.g. Master, Develop]
 - Version [e.g. 3.2.1]
 
**Additional mods used:**
 - e.g CBA_A3 (v3.10.1.190316)

**Additional context**
I have overwritten mission settings in the CBA config.

**Comment by genesis92x** [comment]
Try the "develop" branch - and let me know if you get that error. You will have to use CBA or install the new userconfig folder into the root A3 folder.

**Comment by aussie-battler** [comment]
It is probably because the wrong file is in the folder:

https://github.com/genesis92x/VcomAI-3.0/tree/develop/userconfig/VCOM_AI

AISettingsV3.hpp

Should be AISettingsV4.hpp
