### ISSUE TITLE
VCM_CBASettings Not Found

### ISSUE THREAD

**Issue by 5tratz** [genesis92x/VcomAI-3.0#119]
I am getting this error:

`"Script Vcom\Functions\VCM_CBASettings﻿.sqf not found"`

The old script version has it, but the new 3.3.2 download link doesn't have it, I can fix this WITH using the old version "VCM_CBASettings﻿.sqf" in the folder where it's saying can't be found, but is this okay and should it be like this?

Thanks

**Comment by genesis92x** [comment]
Would you double check the download.

I just went through and checked the develop/3.3.2/release 3.3.2 and it looks like the issue should be resolved.

**Comment by 5tratz** [comment]
No mate just tried em all ... 

VcomAI-3.0-3.3.2 (doesn't have)
VcomAI-3.0-release-3.3.2 (doesn't have)
VcomAI-3.0-develop (does have)
VcomAI-3.0-master (does have)

Look here, it isn't there: https://github.com/genesis92x/VcomAI-3.0/tree/release/3.3.2/Vcom/Functions 

I am wanting it for the latest release 3.3.2 of course so.

Thanks :)

**Comment by genesis92x** [comment]
I am assuming that the error is coming from this file
https://github.com/genesis92x/VcomAI-3.0/blob/release/3.3.2/description.ext

You have an out of date description.ext? Check to see if it reads:

```
class Extended_PreInit_EventHandlers {
	VCM_CBASettings = call compile preprocessFileLineNumbers "Vcom\Functions\fn_CBASettings.sqf";
};

```
It needs to read

```
class Extended_PreInit_EventHandlers {
	VCM_CBASettings = call compile preprocessFileLineNumbers "Vcom\Functions\VCM_Functions\fn_CBASettings.sqf";
};
```

I just checked the develop branch, it's not in the functions folder... which is correct.

https://github.com/genesis92x/VcomAI-3.0/tree/develop/Vcom/Functions

Did you download again in the past 24 hours? The GitHub was just updated.

Thank you :)

**Comment by 5tratz** [comment]
Hm,.. seems I missed that, my bad then I suppose, so sorry for pointing it out, I will open my eyes better next time :D

Thanks again :)

**Comment by genesis92x** [comment]
No problem, glad we worked it out. Thanks for the report
