### ISSUE TITLE
[CLOSED] Ai Steal Locked Vehicle

### ISSUE THREAD

**Issue by aussie-battler** [genesis92x/VcomAI-3.0#12]
Great work on the mod, thanks for putting in so much time & effort.

I have run Exile servers & notice that locked vehicles get stolen. I searched the code & think that it is called from this line:

Vcom\FSMS\SQADBEH.fsm     line 463

`                         "	if (_x iskindof ""LandVehicle"" && {crew _x isEqualTo []} && {_x distance _Leader < VCM_AIDISTANCEVEHPATH} && {!(locked _x isEqualTo 2)}) then" \n`

Just wondering if it works on other non-exile servers? 

I thought maybe this:
{!(locked _x isEqualTo 2)})
Should be:
{!((locked _x) isEqualTo 0)})  

I think arma3 locked vehicle = 2 & unlocked = 0

If locked vehicles cant be stolen on other servers I'll start trying exile coding.

cheers.

aussie

**Comment by aussie-battler** [comment]
Also I was looking at ai steal all vehicles. Would this be the correct code?
`" if ((_x isKindOf "LandVehicle") || (_x isKindOf "Air") || (_x isKindOf "Ship") && {crew _x isEqualTo []} && {_x distance _Leader < VCM_AIDISTANCEVEHPATH} && {!((locked _x) isEqualTo 2)}) then" \n`

**Comment by aussie-battler** [comment]
I think it is suppose to read:
`&& {!(locked _x isEqualTo 0)}) then" \n`

**Comment by aussie-battler** [comment]
No, that didnt work....

**Comment by aussie-battler** [comment]
&& {!(_x lock false)}) then" \n

doesnt work, the ai ignore cars, must be my bad coding...

**Comment by aussie-battler** [comment]
The ai still got in a locked vehicle with this:

`"	if (_x iskindof ""LandVehicle"" && {crew _x isEqualTo []} && {_x distance _Leader < VCM_AIDISTANCEVEHPATH} && {!(_x lock false)}) then" \n`

Maybe its an Exile thing. I'll try exile calls.

**Comment by aussie-battler** [comment]
MAYBE THIS??
`                         "	if (_x iskindof ""LandVehicle"" && {crew _x isEqualTo []} && {_x distance _Leader < VCM_AIDISTANCEVEHPATH} && {!(locked _x isEqualTo 2)}) exitWith {};" \n
                         "	if (_x iskindof ""LandVehicle"" && {crew _x isEqualTo []} && {_x distance _Leader < VCM_AIDISTANCEVEHPATH} && {!(locked _x < 2)}) then" \n	`

**Comment by genesis92x** [comment]
Hey Aussie! For some reason I missed this thread. I have found the locked vehicles to still be an issue from time to time - I have noticed that if the AI add the vehicle to their group BEFORE a vehicle is locked, they will still enter it. It's rather frustrating

**Comment by genesis92x** [comment]
Regardless if it's an issue with Vcom or Exile, I'd like to find a more reliable way for players to control what vehicles AI will steal - without making it a setvariable.

**Comment by aussie-battler** [comment]
Thanks for the advice. Great work on Vcom. Your youtube videos are great to help understand how to code ai.

Keep up the good work.

**Comment by aussie-battler** [comment]
@freddo3000

I couldnt get your fix to work. 
I might try:

"_isNOTlocked = locked _x < 2;" \n						 
"if (_x iskindof ""LandVehicle"" && {crew _x isEqualTo []} && {_x distance _Leader < VCM_AIDISTANCEVEHPATH} && {_isNOTlocked}) then" \n

**Comment by Freddo3000** [comment]
Are you setting it to locked in Zeus? Because in Zeus Locked doesn't actually mean locked, it means "locked for players", something that I found out.
