### ISSUE TITLE
VCOM Does not check if check if closest enemy is aircraft

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#13]
Currently, this causes the COVER2COVER part of the FSM to send AI chasing after aircraft. Adding a check to see if target is an aircraft in the Combat Brain would solve this issue.

**Comment by aussie-battler** [comment]
Cheers @Freddo3000 

Maybe I will try coding in the command at the top of the config when ai are spawned in.

  (group this) setVariable ["Vcm_Disable",true]; //This command will disable Vcom AI on a group entirely.

They will currently hop in a passing vehicle or walk a few kilometers away from their mission. They use to just stay in the one spot.

**Comment by Freddo3000** [comment]
Fixed with #28
