### ISSUE TITLE
Replace Userconfig with CBA completely and full CBA integration

### ISSUE THREAD

**Issue by AndreasBrostrom** [genesis92x/VcomAI-3.0#144]
**Is your feature request related to a problem? Please describe.**
A full integration would allow for some mission side usage as well as allow adjustment of values from addon settings without requiring the mission to be started first.

**Describe the solution you'd like**
Removal of UserConfig and utilize CBA Settings completely.

**Describe alternatives you've considered**
Some hard values could be saved as global.

**Additional context**
Nothing that have already been stated.

**Comment by tyl3r99** [comment]
I think this can be closed now 😊
