### ISSUE TITLE
VCOM AI not showing up in CBA settings

### ISSUE THREAD

**Issue by Drift91** [genesis92x/VcomAI-3.0#156]
**Describe the bug**
9 times out of 10 VCOM AI doesn't show up in the CBA settings.

**To Reproduce**
1. Open CBA's "addon options"
2. Look for VCOM AI in the list. It's not showing up most of the time.

**Expected behavior**
VCOM AI be listed in the addon options of CBA.

**Screenshots**
![20200411160951_1](https://user-images.githubusercontent.com/2638764/79054113-3fcde300-7c10-11ea-93a3-72bbb1a94476.jpg)

**VCOM Version:**
 - Branch: [Steam]
 - Version [3.3.3]
 
**Additional mods used:**
 - CBA_A3 v3.15.0

**Additional context**
When the bug occurs, this gets spammed in my client's .RPT file:
```sqf
16:11:36 Error in expression <!Vcm_DrivingActivated>
16:11:36   Error position: <Vcm_DrivingActivated>
16:11:36   Error Undefined variable in expression: vcm_drivingactivated
```

---

**Original Post:**
> **Describe the bug**
> 9 times out of 10 VCOM AI doesn't show up in the CBA settings. I'm not sure if this is possibly a limit to the size of the list of mods in CBA or if it's a bug in VCOM AI detecting CBA.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Open CBA's "addon options"
> 2. Look for VCOM AI in the list. It should be close to the bottom with the below modpack, but it's not showing up most of the time.
> 
> **Expected behavior**
> VCOM AI be listed in the addon options of CBA.
> 
> **Screenshots**
> N/A
> 
> **VCOM Version:**
>  - Branch: [Steam]
>  - Version [3.3.3]
>  
> **Additional mods used:**
>  - Launcher Preset: http://s000.tinyupload.com/index.php?file_id=30509845128418098534
> 
> **Additional context**
> N/A
>

**Comment by shukari** [comment]
Same here... many times VCOM is not registered at CBA settings

**Comment by AndreasBrostrom** [comment]
You need to start a mission to get Vcom to show up its not.

**Comment by Drift91** [comment]
I just updated the OP. Not sure why I didn't think to test without my modpack in the first place since that could have easily been the cause. However it still occurs even with just CBA and VCOM.


> You need to start a mission to get Vcom to show up its not.

You need to start a mission to even get into the addon options in the first place.

**Comment by genesis92x** [comment]
`16:11:36 Error in expression <!Vcm_DrivingActivated>
16:11:36   Error position: <Vcm_DrivingActivated>
16:11:36   Error Undefined variable in expression: vcm_drivingactivated`

That error suggests that Vcom AI is not installed correctly, or you are using an old/corrupt userconfig file.
