### ISSUE TITLE
ACE compability: Problems with unconscious AI

### ISSUE THREAD

**Issue by danvac** [genesis92x/VcomAI-3.0#159]
**Describe the bug**
When playing with ACE Medical, unconscious AI units are placing satchels, mines, etc.

**To Reproduce**
1. Prepare demolition expert near enemy building
2. Injure him so it will gen unconscious
3. Wait
4. It will place satchel, mines or maybe also can call reinforcements

**Expected behavior**
Unconscious AI should not be doing anything

**VCOM Version:**
 - Version 3.3.0
 
**Additional mods used:**
 - ACE version 3.13.0

**Comment by genesis92x** [comment]
Resolved! I think. Post if the error continues. Thank you!
