### ISSUE TITLE
Stop forcing setSpeedMode "FULL"

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#16]
Doing this removes control from zeuses and mission makers, as they do not always want the AI outright charging a position.

**Comment by aussie-battler** [comment]
You should put the file and line number the code is called from. Genesis isnt getting paid for Vcom and it just wastes his' time trying to look for code which you probably have in front of you. 

Maybe even suggest what speed you would like it set to that would make it work.  Try even limitSpeed to 20 and see if that works for you. 

https://community.bistudio.com/wiki/limitSpeed

**Comment by Freddo3000** [comment]
Limit speed is nothing that has to do with this, setSpeedMode has three modes, which is quite literally "LIMITED", "NORMAL" and "FULL". While I do have to admit that I probably should've mentioned where it is in the FSM, at the same time it is quite literally ctrl + F "setSpeedMode" to find it.

**Comment by genesis92x** [comment]
Unfortunately this is one of the few ways to get AI to actually move around the world with any consistency. Zeus players should be utilizing waypoints or other methods of controlling AI movement. How does this impact the AI being in STEALTH mode, for example? I have generally believed these extra modes to be useless.

**Comment by Freddo3000** [comment]
Made configurable with #28
