### ISSUE TITLE
Vcom script 3.4.0 dev does not work in SP editor 

### ISSUE THREAD

**Issue by tyl3r99** [genesis92x/VcomAI-3.0#161]
**Describe the bug**
A clear and concise description of what the bug is. >> when in the editor and you have the script version of the 3.4.0, it does not work unless you play in MP <<

**To Reproduce**
1. Go to '...' editor and place down a player unit, and a game master module. Give your player a variable name and put it into zeus module owner field.
2. Click on '....' play at the bottom right 
N/a
4. Enable debug mode through CBA and you'll notice it does not work. However if you click play at the top right and click play in MP.. it works 

**Expected behavior**

I would have thought it would work anywhere? 

**Screenshots**

**VCOM Version:**
 - Branch: [dev build]
 - Version 3.4.0
 
**Additional mods used:**
 - e.g CBA_A3 up to date since 30th june 2020

**Additional context**
I will try attach a zip of my mission file later on but its simply a player and game master module so it's easy to set up yourself

**Comment by genesis92x** [comment]
Resolved! Nice catch!
