### ISSUE TITLE
Nato MLRS "no ammo" debug mode 3.4.0 dev

### ISSUE THREAD

**Issue by tyl3r99** [genesis92x/VcomAI-3.0#162]
**Describe the bug**
A clear and concise description of what the bug is. >>the MLRS nato arty tank does not work with vcom. With debug mode enabled it says "no ammo" 

I've tried putting the tank at multiple distances however remains the same 

**To Reproduce**
1. Make yourself a zeus in a game 
2. Make a firefight 
3. Spawn a MLRS NATO tank 
4. Enable debug mode 
5. Observe 

**Expected behavior**

**Screenshots**

**VCOM Version:**
 - Branch: [develop]
 - Version [e.g. 3.4.0]
 
**Additional mods used:**
 - e.g CBA_A3 up to date as of 30th june 2020

**Additional context**
Rpt showed this error 

13:45:46 Cannot create non-ai vehicle APERSMine_Range_Ammo_scripted,

**Comment by genesis92x** [comment]
Resolved!
