### ISSUE TITLE
Script error 3.4.0dev

### ISSUE THREAD

**Issue by tyl3r99** [genesis92x/VcomAI-3.0#163]
**Describe the bug**
A clear and concise description of what the bug is. >>experienced an on screen script error while testing 3.4.0dev I'll copy the error down below<<

**To Reproduce**
I was unable to reproduce this issue

**Expected behavior**
N/A

**Screenshots**
See discord vcom bug reports 30th june 2020

**VCOM Version:**
 - Branch: [Develop]
 - Version [e.g. 3.4.0]
 
**Additional mods used:**
 - e.g CBA_A3 up to date as of 30th june 2020

**Additional context**

also got this in RPT 
13:54:54 Error in expression <_PredictedLoc = (_NearestFriendly2Enemy targetKnowledge (vehicle _NearestEnemy))>
13:54:54   Error position: <targetKnowledge (vehicle _NearestEnemy))>
13:54:54   Error targetknowledge: Type Array, expected Object
13:54:54 Error in expression <_PredictedLoc = (_NearestFriendly2Enemy targetKnowledge (vehicle _NearestEnemy))>
13:54:54   Error position: <targetKnowledge (vehicle _NearestEnemy))>
13:54:54   Error Generic error in expression
13:54:57 Error in ReloadMagazine - unable to locate target weapon arifle_Katiba_C_F muzzle arifle_Katiba_C_F
13:54:58 Error in expression <_PredictedLoc = (_NearestFriendly2Enemy targetKnowledge (vehicle _NearestEnemy))>
13:54:58   Error position: <targetKnowledge (vehicle _NearestEnemy))>
13:54:58   Error targetknowledge: Type Array, expected Object

**Comment by genesis92x** [comment]
Attempted a fix! Report again if this bug pops up
