### ISSUE TITLE
VCOM Building is overly aggressive

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#19]
It currently is getting called every 15 seconds which in my opinion is a bit too often, and also seems to lack any check for how far away the building is.

**Comment by aussie-battler** [comment]
Hi, It does check how far a building is (it checks if a building is within 25m of an enemy unit) :

//Function that allows AI to clear a garrisoned building
params ["_Group","_Enemy"];

private _nBuildingLst = nearestObjects [_Enemy, ["House", "Building"], 25];

**Comment by aussie-battler** [comment]
private _nBuildingLst = nearestObjects [_Enemy, ["House", "Building"], 25];

VCOM code is pretty solid. You should take time to read the code before throwing it under the bus. The enemy is included in the above call. 

Nearest objects include both buildings and the enemy within 25 meters.

**Comment by Freddo3000** [comment]
I think you've misinterpreted what I said.

The code checks if the enemy unit and the building is within 25m of one another. What I meant was the AI starts running house clearing code even though BLUFOR and OPFOR are several hundred meters away from one another.

I've confirmed this behaviour by adding debug messages to the script.

**Comment by genesis92x** [comment]
Thanks for the information - I will take a look at it. I will be looking at this

**Comment by Freddo3000** [comment]
Fixed with #28
