### ISSUE TITLE
fn_ArtyCall seems to ignore the 15m min distance

### ISSUE THREAD

**Issue by ninjaProtocol** [genesis92x/VcomAI-3.0#20]
Hello!

We ended up seeing some pretty accurate mortar fire, so I decided to look at what target position was passed to the artillery units. Looking at the code, the distance is calculated as:
`private _dist = random (15 + (random VCM_ARTYSPREAD));`
There are two `random` commands, for some reason. The outermost one makes the 15 pointless, since you're in effect getting `0` to `VCM_ARTYSPREAD + 15`. I assume the intention was to set 15 as the minimum radius? This would be nice anyway, getting blown up without warning isn't great fun.

I suppose this is something people may differ in opinion about, so I suggest considering the other syntax for `random`, such as `random [15, (15+VCM_ARTYSPREAD)/2, VCM_ARTYSPREAD]`, and/or allowing min, mid and max values to be configured via userconfig.

Even if you decide to stick to the uniform distribution, making the minimum value user configurable would be great.

Cheers

**Comment by genesis92x** [comment]
Nice catch, beautiful write up. I appreciate the hard work.

Expect this to be fixed in the next version :)
