### ISSUE TITLE
[SOLVED] AI leave mission.

### ISSUE THREAD

**Issue by aussie-battler** [genesis92x/VcomAI-3.0#21]
Hi 
I am loving Vcom, but ai are leaving missions to join other units.

I tried setting mission ai to civilian and Vcom ai to side east. However Vcom ai still call them away from the misson area.

I also did this:
 	VCM_HEARINGDISTANCE = 50; //Distance AI hear unsuppressed gunshots.
	VCM_WARNDIST = 50; //How far AI can request help from other groups.

Is there something that I am missing? I am using Arma3 Exile with DMS for missions.

Cheers

**Comment by Freddo3000** [comment]
It has to do with these issues. #13 #14 #19

**Comment by aussie-battler** [comment]
@Freddo3000 Thanks for the heads up. Maybe the user config isn't being used  by Vcom.

When I press escape = configure = addon options = Vcom settings = server

The config is still using default Vcom settings. Do you have the problem or does changing the config work for you?

**Comment by aussie-battler** [comment]
Ill try adding these calls when mission ai spawn in:

_group setVariable ["Vcm_Disable",true];
_group setVariable ["VCM_NORESCUE",true]; //This command will stop the AI squad from responding to calls for backup.
_group setVariable ["VCM_TOUGHSQUAD",true]; //This command will stop the AI squad from calling for backup.

**Comment by aussie-battler** [comment]
I fixed it by putting my mission & roaming ai on different sides. The ai fight each other but that all part of the battlefield.
