### ISSUE TITLE
Disable AI from going prone.

### ISSUE THREAD

**Issue by n0dane** [genesis92x/VcomAI-3.0#23]
Is there any way to completely disable AI from going prone?

Some maps have high grass that is where prone AI is a big hassle, a toggle to not allow AI going prone would make those missions so much more enjoyable

**Comment by Freddo3000** [comment]
Unfortunately not, however you can put:

```
class CfgSurfaces {
    class Default { 
        AIAvoidStance = 2; 
    }; 
};
```
in a config.cpp, which will make the AI avoid going prone as much as possible. Beware though, using this method will affect all maps.

**Comment by n0dane** [comment]
Will try that, Thanks :)
