### ISSUE TITLE
AI never return to normal behaviour

### ISSUE THREAD

**Issue by Andrees97** [genesis92x/VcomAI-3.0#25]
AI that gets new waypoints assigned as a result of VCM_ADVANCEDMOVEMENT never return to normal behaviour (ie patrolling), have still to test this with waypoint based patrol systems, but UPS for example gets broken.

**Comment by Andrees97** [comment]
I fixed this by modifying the FSM and adding a check that disables combat mode and resets the unit behaviour to LIMITED and SAFE so they can resume patrol.
NOTE: I also removed a few instances (static weapons deployment) that I didn't need and for some reason can't seem to turn off via settings.

[Vcom.zip](https://github.com/genesis92x/VcomAI-3.0/files/2377044/Vcom.zip)

**Comment by xetra11** [comment]
make a Pull Request or a git patch

**Comment by genesis92x** [comment]
Thanks for the upload! I took a look at what you did and implemented it. I modified it to fit with the new version better. Thanks for the help!
