### ISSUE TITLE
fn_HearingAids locality issues

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#33]
#32 
This pull request was approved while still needing changes.

https://github.com/genesis92x/VcomAI-3.0/blob/966090b163f91d458747ed5c488cc3ece255620d/Vcom/Functions/fn_HearingAids.sqf#L9-L10

The presence of `player` may cause locality issues and should be `_unit` instead.

**Comment by Freddo3000** [comment]
I'll be putting up a pull request shortly.

**Comment by genesis92x** [comment]
I went ahead and resolved this! Thanks Freddo, I am looking to publish an update here tonight.
