### ISSUE TITLE
Consider integrating Fire for Effect: God of War

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#40]
https://forums.bohemia.net/forums/topic/159152-fire-for-effect-the-god-of-war-smart-simple-ai-artillery/

It uses the same license as Vcom and openly states that you can use the script however you want.

It has a significant amount of functionality that Vcom artillery doesn't have, and I figure that we integrate it in order to not reinvent the wheel.

**Comment by xetra11** [comment]
Please say yes 💃

**Comment by genesis92x** [comment]
Approved it, I am currently doing further testing for stability. If there are stability concerns we will take what we can learn from the mod and implement them into Vcom.
