### ISSUE TITLE
Error "COMBAT" and "Missing ;"

### ISSUE THREAD

**Issue by jus61** [genesis92x/VcomAI-3.0#44]
Vcom AI 3.1 Download 11.11.2018

11:08:37 Error in expression <(leader (group _Unit)) < 500} && {_Unit behaviour isEqualTo "COMBAT"}} do
{
slee>
11:08:37   Error position: <behaviour isEqualTo "COMBAT"}} do
{
slee>
11:08:37   Error Missing ;
11:08:37 File Vcom\Functions\VCM_Functions\fn_ArmStatics.sqf [VCM_fnc_ArmStatics], line 49
11:08:37 Error in expression <(leader (group _Unit)) < 500} && {_Unit behaviour isEqualTo "COMBAT"}} do
{
slee>
11:08:37   Error position: <behaviour isEqualTo "COMBAT"}} do
{
slee>
11:08:37   Error Missing ;
11:08:37 File Vcom\Functions\VCM_Functions\fn_ArmStatics.sqf [VCM_fnc_ArmStatics], line 49

**Comment by Freddo3000** [comment]
behaviour and _Unit is the wrong way around
