### ISSUE TITLE
Addon Version of 3.1

### ISSUE THREAD

**Issue by LtJulius** [genesis92x/VcomAI-3.0#47]
We would try VCOM 3.1 but with a server and private repository and multiple missions it's not usable as script version.

So please take care of addon version to release ;)

**Comment by Freddo3000** [comment]
Expect an addon release this weekend.

**Comment by aussie-battler** [comment]
@freddo thanks for your hard work in putting 3.1 together. Ill be putting on our servers. 

Looking forward to the release  :)
