### ISSUE TITLE
CBA settings not functional in addon

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#49]
`Script Vcom\Functions\VCM_CBASettings.sqf not found`

**Comment by diveyez** [comment]
No fix yet?

**Comment by genesis92x** [comment]
I shouldn't even say anything but it's been a long week, diveyez that's incredibly annoying, Freddo and I both do this in our free time, for free. If the CBA settings are not working you can change the settings in the userconfig folder and enable filepatching. It's been less than 24 hours.

**Comment by Freddo3000** [comment]
Resolved with update
