### ISSUE TITLE
ALiVE chopper still seem to be influenced by VCOM 3.0

### ISSUE THREAD

**Issue by NZF-JDWang** [genesis92x/VcomAI-3.0#5]
I've read people complain about this on the ALiVE forums and I hadn't seen it happen until tonight when I logged into the server and all the ALiVE combat support choppers were hovering together over the middle of the airbase.

I have since added the `(group this) setVariable ["Vcm_Disable",true];` code into the combat support modules, but even after that saw my CAS chopper decide to head out again after I had told it to RTB (which it had done) 

Will try running some tests over the weekend with no mods other than CBA and ALiVE to see if I can reproduce this.

**Comment by xetra11** [comment]
Mybe the debug loggin addition could help with analyzing that issue

**Comment by aussie-battler** [comment]
@NZF-JDWang 

I dont have Alive, but had a similar problem. You can solve it by changing Alive _group side to the opposite of Vcom (they fight each other) :)

https://community.bistudio.com/wiki/Side_relations 

or 

You can add this code after the ai chopper is spawned & added to a _group (rename it to the _group name):

```
_group setVariable ["VCM_TOUGHSQUAD",true];
_group setVariable ["VCM_NORESCUE",true];

```
