### ISSUE TITLE
Disable formation change while in convoy

### ISSUE THREAD

**Issue by Tee-ee-ee** [genesis92x/VcomAI-3.0#50]
The AI-driven convoy tends to change formation based on the terrain. I don't want to set "VCM_FRMCHANGE = false" since I still want the infantry AI to be able to change formation. Would it be possible to disable AI capability to change formation only when they are in convoy and their behavior is "safe", sth like:

if (unit is in vehicle && behavior is safe) then {VCM_FRMCHANGE = false; //or force formation "Column"} //but only apply to the units in the convoy

It looks strange when a column formation convoy tries to go into a line formation when there is no threat.

**Comment by Freddo3000** [comment]
Vehicle groups will now form columns when in safe mode. See f6c42083b381c4c34816253677b5e25726df9b47
