### ISSUE TITLE
[Addon Ver.] If CBA addon enabled on server, the userconfig file does not take any effect.

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#51]
I've found a possibly bug of VcomAI-3.1.

If CBA addon enables on server and uses cba_settings.sqf as configuration, no matter if VCOM Settings are defined in the cba_settings.sqf file, the AISettingsV3.hpp userconfig file does not take any effect. This happens both on dedicated server and client hosted server.

However, as this issue(https://github.com/genesis92x/VcomAI-3.0/issues/49) described, userconfig file should work with CBA enabled, even if CBA Settings not functional.

Besides, I'd like to know which one will take effect if both CBA Settings(cba_settings.sqf) and userconfig file(AISettingsV3.hpp) are defined.

**Comment by Freddo3000** [comment]
#49 mentioned using userconfig as a temporary solution until the CBA issue is fixed.

For now CBA takes priority over userconfig, as you can set server settings with it easier.

**Comment by GoldJohnKing** [comment]
I means if I use CBA Settings to configure addons like ACE3 while using the userconfig file to configure VCOM, the VCOM settings does not take any effect. This is a critical issue while I want to use both CBA Setting configured addons and VCOM, The VCOM settings will never take effect in this condition.

**Comment by Freddo3000** [comment]
As is right now the priority is as follows

Mission settings >> CBA Settings >> userconfig >> default settings

Do note that it is overwriting and not replacing. Mission settings overwrite CBA settings, CBA settings overwrite userconfig. This means that if there is no option in CBA for something mentioned in userconfig, the userconfig will not be overwritten.

I hope this clarifies any issue you might have.

**Comment by Freddo3000** [comment]
https://github.com/genesis92x/VcomAI-3.0/blob/16a98674a392edee2aae1d77532ce59845dca870/Vcom/VcomInit.sqf#L5-L36

Looking here that should not be the case. If your userconfig is where it is supposed to be and filepatching is enabled, it should always take priority over default settings. Can you confirm that the userconfig works if you disable CBA?

**Comment by GoldJohnKing** [comment]
Yep. I'm sure my userconfig is where it suppose to be and filepatching is enabled, or I cannot even load my CBA Settings. And I Confirmed that the userconfig works without CBA.

The whole situation is like this:

Situation A | Situation B | Situation C
-- | -- | --
CBA Enabled. | CBA Disabled. | CBA Enabled but VCOM parameters not defined in it.
Use CBA Settings to define VCOM parameters. | Use Userconfig to define VCOM parameters. | Use Userconfig to define VCOM parameters.
Custom Settings Applied. | Custom Settings Applied. | Default Settings Applied, Usercofig Settings Ignored.

To make sure, here's the screenshot of the CBA & VCOM userconfig files' location.
![36](https://user-images.githubusercontent.com/26923626/48989612-f5a4a880-f165-11e8-83a5-e8b566fff8fe.png)

**Comment by Freddo3000** [comment]
May I ask what settings you are trying to change? I know that VCM_SKILLCHANGE is broken in the current release.

**Comment by GoldJohnKing** [comment]
VCM_SKILLCHANGE is one of the problem. 
However, my main purpose is to report a potential bug, not to change the params. 
By the way, default settings are already hard enough for normal player.

**Comment by Aarnoman** [comment]
Is this still occuring on the current development branch? As I understand it, it is caused from load order priority (Mission settings >> CBA Settings >> userconfig >> default settings). Maybe add a comment in the userconfig file stating that CBA settings take priority and consider closing this issue otherwise?

**Comment by Aarnoman** [comment]
Could you specify what this strange behaviour is, and any way of replicating it?

**Comment by Freddo3000** [comment]
On point 2, that is because the current behavior is mainly stock-like behavior, at least on the per-unit scale. VCOM 2 had a significant amount of changes here, but it was later deprecated in 3.0 to improve performance. I'll look into working on it in 3.3, see #64.

I know that point 3 has to do with #11, and is a vanilla issue.

The rest I will investigate.

**Comment by Freddo3000** [comment]
Cannot replicate point number 1 and 4.

**Comment by Freddo3000** [comment]
Would you mind creating a separate issue?

**Comment by Aarnoman** [comment]
In regards to point 4, the current release version of vcom doesn't apply ai skill settings correctly.  This is fixed in the current development build. May be worth pushing a hotfix for it at some point as it is a somewhat significant issue @freddo3000

**Comment by Freddo3000** [comment]
@Aarnoman I'm currently working on release 3.2, so that is coming sooner or later. Unfortunately I cannot push the update to steam myself, only @genesis92x can do it, and he is fairly busy as it seems right now.

**Comment by Aarnoman** [comment]
@Freddo3000 no worries just happy it is in the pipeline, we're using last weeks dev build until it gets pushed to release.

**Comment by GoldJohnKing** [comment]
I noticed a much more detailed and analyzed issue related to this problem was opened, so this issue is no longer needed, so I closed the issue, anyone need to discuss about this issue, please move to https://github.com/genesis92x/VcomAI-3.0/issues/67 .Thanks a lot for all your efforts on this project.
