### ISSUE TITLE
Integrate "Smarter Tanks" by Alarm9K

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#55]
https://github.com/genesis92x/VcomAI-3.0/tree/feature/SmarterTanks

As it seemingly has been largely abandoned, and the license permits, I think we should consider integrating "Smarter Tanks" into VCOM.

Todo:

- [x] Transfer to functions library
- [ ] Refactor script
- [ ] Make "ammo" detection automatic
- [ ] Integrate into CBA settings
- [ ] Optimize where able
- [ ] Add comments
- [ ] Check compatibility with VCOM Driving

[Forum topic](https://forums.bohemia.net/forums/topic/172270-smarter-tanks-script/)

**Comment by SekiAlpha** [comment]
The mod author of this upload is active though.
https://steamcommunity.com/sharedfiles/filedetails/?id=1352437763

**Comment by Freddo3000** [comment]
Starting work on refactoring this script, and moving it to FSM

**Comment by threedots1** [comment]
Really interested in how this goes. Running a slightly improved version with VCOM and the WW2 half tracks tend to charge off alone after dropping their troops off and are killed off. Once your FSM version is up I'll be keen to help improve it

**Comment by genesis92x** [comment]
It might be a better idea to make Vcom compatible with this mod - as it looks like Alan is still active with his steam version?
