### ISSUE TITLE
Integrate Ai skill settings into CBA options

### ISSUE THREAD

**Issue by Aarnoman** [genesis92x/VcomAI-3.0#57]
Feature Request: Add sliders for AI skill values (specifically aimingAccuracy, aimingShake, aimingSpeed) in the VCOM addon options in the CBA settings menu, to allow easy finetuning of AI difficulty for endusers without having to use filepatching/userconfig edits, while also enabling server > client transfer of values in Zeus scenarios. This would also allow on the fly editing of AI skill settings in case of a dynamic scenario where difficulty changes.

Happy to sort out the code for this myself with your permission.

**Comment by Aarnoman** [comment]
I've created the necessary changes and can publish a fork if you are able to assign me the required permission.

**Comment by Freddo3000** [comment]
The files here on github are made in a way to simply be able to drop in a mission and go. To convert it into a mod you need a config.cpp file, which needs to be set up in a different way. Description.ext for reference is used in missions.

Here are some useful resources:
* https://community.bistudio.com/wiki/Config.cpp/bin_File_Format  
* https://community.bistudio.com/wiki/CfgPatches  
* https://community.bistudio.com/wiki/Functions_Library_(Arma_3)  
* https://community.bistudio.com/wiki/Functions_Library_(Arma_3)#Attributes  
* And probably most important: [Community Based Addons 3](https://github.com/CBATeam/CBA_A3/wiki)

**Comment by Aarnoman** [comment]
Thank you for the helpful links and explanation. Have successfully managed to test the branch on a mission now, this is a much more efficient way of developing anyway. I will work on my understanding of the config.cpp soon. Thank you again.

**Comment by Aarnoman** [comment]
AI Skill options has been merged into the development branch.
