### ISSUE TITLE
VCOM and High Command

### ISSUE THREAD

**Issue by JohnAlbritton** [genesis92x/VcomAI-3.0#6]
Am trying to use VCOM with a BECTI mission that I believe runs off of the Arma HC module.

I can issue orders to the AI units to take the first objective but after that I lose control of the units. I give the take and hold command on the in game cti menu but the ai units just ignore it.

Using the Advanced AI mod I can issue waypoints on the general map that the AI will follow but even then they tend to wander off on their own.

**Comment by genesis92x** [comment]
This will require some changes with BECTI and the VCOMAI settings with the mission. I am able to control the AI with ZEUS. I am not sure how BECTI differs in this regard.
