### ISSUE TITLE
Bug, infantry squads follow apc

### ISSUE THREAD

**Issue by HayesRus** [genesis92x/VcomAI-3.0#61]
i spawned 4 infantry squads and 4 separate apc with crew, synced them to high command module and when i start mission infantry squads gether around one of apc and dont follow any waypoints, if apc move they running with that apc, this happens even without high command

**Comment by HayesRus** [comment]
i have set "Mag count ai begin to look for additional mag" to 2 and they dont follow apc now, but i think if they run out of ammo this will happen again.

**Comment by Freddo3000** [comment]
Are the units part of a mod, and do they have enough inventory space to rearm? The issue may lie in that.

**Comment by HayesRus** [comment]
vanilla Nato faction

**Comment by HayesRus** [comment]
each of them have at least 5 mags

**Comment by Freddo3000** [comment]
Try removing tracer mags from the unit

**Comment by HayesRus** [comment]
i think i found why this happens, they cant reach ammo for resupply, i moved unit without ammo manualy with zeus close to apc and he rearmed himself

**Comment by Aarnoman** [comment]
I can confirm this issue. Spawned one NATO rifle squad. Spawned 1 Marshall. CBA Settings AI magcount set to 10. Set move order as Zeus. Rifle Squad will get 'stuck' around APC and ignore further move orders.

**Comment by Freddo3000** [comment]
Found the issue, AI would approach the APC but never be able to get close enough for the script to finish. I'll be lowering the `VCM_AIMagLimit`, and increasing the distance for rearm to be considered "complete".

**Comment by Will-Nichols** [comment]
Was about to comment on this but saw that it is addressed; thanks for the work.
