### ISSUE TITLE
Improve suppression behavior

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#64]
Possibly tie in the [vanilla suppression system](https://community.bistudio.com/wiki/AI_Morale), with some additional reactions depending on the current amount of suppression.  
Examples being:

- opting to stay prone/crouched more
- throwing smoke grenades
- issuing suppressive fire orders
- opting to fall back

Further ideas/thoughts are appreciated.

**Comment by Will-Nichols** [comment]
AI places mines when killed or shot at way too often; I have my AISettingsV3.hpp file set with `	VCM_MINECHANCE = 10; //Chance to lay a mine` and they still place a mine each time they are killed or suppressed.

**Comment by Will-Nichols** [comment]
Having AI do a little more recon on probable/known targets before just rushing into a situation; maybe some way to tell them to probe an area depending on how many AI forces are nearby to support/assist?

**Comment by Freddo3000** [comment]
@Aarnoman looking at [the steam page](https://steamcommunity.com/linkfilter/?url=https://www.bistudio.com/community/licenses/arma-public-license-share-alike) it is seemingly licensed under [APL-SA](https://www.bohemia.net/community/licenses/arma-public-license-share-alike), the same license as VCOM.

**Comment by threedots1** [comment]
I have ran some MP games with TWPCAS a few weeks ago and it is functionally great but a little performance heavy. It does have a built in 'limiter' where it stops itself running if server fps drops below 10 however...

I feel like compromises or some very clever optimisations would need to be made to keep performance reasonable but it is very immersive as is.

**Comment by Aarnoman** [comment]
@freddo3000 I believe the extra license requirements are located in the readme file of the mod download itself. The steam upload is not by the original author, and goes against the original license set up by tpw.
