### ISSUE TITLE
AI stuck in the building

### ISSUE THREAD

**Issue by Alloc186** [genesis92x/VcomAI-3.0#65]
Hi can you please chech my mission. AI behaviour never lets move Blufor out of the building, in mission startup they garrison the nearset building (thats superb) but they never go out even when the battle is over. It seems they are stuck inside. Thank you.

here is the link for my simple mission:
https://drive.google.com/file/d/1lou9LVn0maqbsUNnVitZEOgQdWesCLEr/view?usp=sharing

**Comment by Freddo3000** [comment]
Do you assign it a different waypoint later? The AI will stay garrisoned as long as they have a "hold" waypoint.

**Comment by Alloc186** [comment]
Blufor got no waypoint assigned. Only one Opfor group has Search and destroy from the mission start. Blufor move to building and call for support from neraby friendly group.

**Comment by Freddo3000** [comment]
The "HOLD" waypoint is a type of waypoint that never finishes, and as long as the group has it it will stay garrisoned. Therefore if you want it to leave garrison, you'll either need to script it or remove the waypoint as Zeus.
