### ISSUE TITLE
AI not functioning according to AIsettingsV3.hpp file

### ISSUE THREAD

**Issue by Will-Nichols** [genesis92x/VcomAI-3.0#67]
In what I believe is close behavior to Issue #51 I have seen the following from AI since the move to the development version from VCOM 3.0.

- I will be building a repro mission with vanilla arma, CBA, VCOM 3.1, and ACE and will follow this up with a 2nd mission utilizing CBA, VCOM 3.1, ACE and Achilles. Then I will do a 3rd mission with CBA, VCOM3.1, ACE, Achillles and ALiVE. 
- Each mission will utilize a cba_settings.sqf file for each one and they will be done on a dedicated server in our community. 
- I may continue to add mods to the mission in order to hopefully track down a mod that is causing the problem provided I do not run across the following example(s) at any time during the first three parts of testing. 

**Example of what I am currently seeing it in a mission I am running using VCOM 3.1 dev version.** 

> The mission does have a large number of mods and I am willing to say that there is a possibility of a mod conflict somewhere; BUT I have done significant testing over the last 6 months with this mission did not see this behavior at all when using 3.0 and have only noticed it when I switched VCOM over to the dev version to give it a shot in our missions. Also I am not going to say that it isn't an issue with either Arma or Achilles either since both items just did an update as well and we all know how Arma loves to break stuff on updates or change a piece of code without giving any update or explanation in the changelog or documentation it seems for months on end.
 I wish I had gotten a video of it last night but we had one AI group that I used an AI helo to get them dropped off via fast rope into the jungle southeast from the ruins in the middle of the main island on the map a little under 1km. That group ran all the way back to the Main airfield on the center island of Tanoa; after I gave them the patrol/loiter order from Achilles and they started to move onto the first point but then the player group used their lasers to point out the AI that were dropped in and once they did that the AI reacted to the players in the area by changing to combat mode. Instead of reacting and going prone or engaging they instead sprinted right at the players (I had the players hold their fire and not engage the AI with anything other than spotting them using lasers) almost 400 meters in front of them and ran all the way back to the airfield. I deleted them and then replaced that unit with another that did the split up and the leader started running back to the main airport while one group of four started walking backwards to the southeast and another group of 3 started walking backwards to the northeast. It did not matter what vanilla or Achilles Zeus command I gave that group they would not change from the behavior they were doing.
> 

As it stands I will most likely be changing back to 3.0 exclusively for missions IF I get this to replicate due to the issue with the points 1 & 4 listed above. On that note here is what the two groups in point 1 did last night.

**Comment by Aarnoman** [comment]
In regards to ai skill settings, there was a bug that I believe has been fixed in #59 where the aidifset routine would never fire.

**Comment by Freddo3000** [comment]
If the AI have NVGs they can see the lasers, however they might not be able to spot the source well enough to engage. I've tweaked the AI movement so that they will hopefully no longer chase units very far away.

**Comment by Will-Nichols** [comment]
Completely understand them being able to see the laser; however they literally ran directly at the source and went through the middle of a group of players that were not in hiding and kept on running. I have a video of the splitting actions today and will post it up by tomorrow my time due to it being so large from a long operation today. I will have to edit down to the unit and the specific time frame and will give the context of what happened.

**Comment by threedots1** [comment]
I have also noticed plenty of situations where the AI become engaged and the squad leader seems to run off by himself towards the squads waypoint while the rest of the squad is actively engaging, taking cover and returning fire. Easy to spot when playing as zeus.

**Comment by Freddo3000** [comment]
@threedots1 that is due to the Squad Leader issuing engage orders to his subordinates, which means that the AI will attempt to move towards and "engage" the target, while he himself cannot be ordered that way. It is a frustrating issue, and one that will be looked upon later for a fix.

**Comment by Will-Nichols** [comment]
[MARSOC team not functioning properly using VCOM against another AI](https://youtu.be/WwTnEP_vdZE)

**Comment by Freddo3000** [comment]
VCOM doesn't, or isn't supposed to touch vehicles. The dismount/remount bug is a vanilla bug as mentioned in #11.

AI getting stuck walking backwards is something I am pretty sure is a vanilla issue. It seems to happen when you move a unit as zeus that is shifting around a piece of cover. VCOM does not have any functionality that I would imagine can cause this, as VCOM only gives destinations for AI to move towards, in regards to movement.

**Comment by Will-Nichols** [comment]
I agree on the Zeus movement but those waypoints were not given by me as the Zeus for that AI on AI mission. Those were randomly generated by the units after I spawned them into the mission. Up until contact the MARSOC units were all in vehicles and after contact they began acting erratically and nothing I did from the Zeus side or even taking them over remotely stopped the activity or caused it to cease. Hell it all might be some random vanilla bug that manifests itself via the RHS unit.

**Comment by Freddo3000** [comment]
Waypoints are generated by VCOM and can be disabled, and in the next release will no longer overwrite zeus placed waypoints.

**Comment by GoldJohnKing** [comment]
> 
> 
> If the AI have NVGs they can see the lasers, however they might not be able to spot the source well enough to engage. I've tweaked the AI movement so that they will hopefully no longer chase units very far away.

I'm using the script version of the latest pre-release v3.2.1, and I've noticed AI has abnormal low willings to execute "long-range" movement. AI seems to refuse reinforce allies further than 300m although the reinforce distance was set to 2500(max) and wait time set to 15s, and those within 300m seems to use a really low speed to move towards players, which makes AI looks awfully lazy. I'm wondering if this commit caused it.

**Comment by Freddo3000** [comment]
@GoldJohnKing open a separate issue.
