### ISSUE TITLE
Possible issue with ALiVE spawned units

### ISSUE THREAD

**Issue by Will-Nichols** [genesis92x/VcomAI-3.0#69]
I posted this issue on the GitHub for ALiVE and thought it might be useful over here as well. 
https://github.com/ALiVEOS/ALiVE.OS/issues/568
We are continuing to find the occasional unit that is spawned into the area near our players or the Zeus camera and this unit starts replicating waypoints like it is going out of style. As I said in the post on the ALiVE GitHub I am not sure this is a VCOM issue but it might be. I do not believe it is related to Fen_A3 as those units are not controlled by or spawned in via Fen when they start this.

**Comment by Freddo3000** [comment]
Doubt it is a VCOM issue, as VCOM will disable waypoint creation once it has more than two waypoints.

**Comment by Will-Nichols** [comment]
Didn't realize that was the case with VCOM in its waypoint creation but that helps me narrow this down. I will close this and then report back if necessary after running through the testing setup to see what happens.
