### ISSUE TITLE
Add more verbose debug logging

### ISSUE THREAD

**Issue by xetra11** [genesis92x/VcomAI-3.0#7]
Hey buddy,
I love your mod and would love to contribute in a few months to support you. Before I do I just wanted to ask if you would add logging to the script to help extending/developing the scripts better in the future?

Greetings

Charlie

**Comment by genesis92x** [comment]
Hey Xetra! Would you explain exactly what you mean by logging? Do you mean adding more commented code, or more debug code?

**Comment by genesis92x** [comment]
I see! That's not a bad idea xetra
