### ISSUE TITLE
Discussion: Change priority from moving towards enemies to moving towards waypoints

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#71]
Need opinion on this. Might add a config option.

**Comment by genesis92x** [comment]
In fn_ForceMove.sqf, it might be worth to take a look at that again. The AI are set to move toward an assigned waypoint, or the nearest enemy, if no waypoint is assigned. I believe I had issues getting the AI to follow domove commands in the latest patch. Even with all the tricks in the book.
