### ISSUE TITLE
[Suggestion]: Behaviour when target is out of sight

### ISSUE THREAD

**Issue by xetra11** [genesis92x/VcomAI-3.0#73]
I do not know anything about FSM. Still I would love to ask if it is possible to add the following behaviour.

When in combat the AI is shooting at the enemy etc. but when the target is getting out of sight - In my opinion the AI is not aggressive enough. In a real situation units will still keep shooting at the last spotted position for a while before acting like the situation changed. Therefore I'd love to see a feature where the AI is still doing "prediction/assumption" fire to the last know targets position.

Is this kinda possible?

greets
Charlie

**Comment by Freddo3000** [comment]
Well, vanilla AI still do this. They'll keep track of your where you were last detected and fire on prediction and where you were last seen, but if you mean for them to do it a minute or two later, that they don't.

**Comment by xetra11** [comment]
Yea I already see what vanilla does... and ye... it isnt aggressive enough you know? But well we can't make it perfect. Was just a wish to have more real combat behaviour
