### ISSUE TITLE
Update Vcom with new version of Fire For Effect: God of War

### ISSUE THREAD

**Issue by HorizonBr** [genesis92x/VcomAI-3.0#75]
Rydygier updated FFE: GoW to 1.16

https://forums.bohemia.net/forums/topic/159152-fire-for-effect-the-god-of-war-smart-simple-ai-artillery/?do=findComment&comment=3327775

Released FFE 1.15. Changelog: 
  - Fixed rare script error when using particular user-made artillery pieces.

Released FFE 1.16. Changelog: 
  - Fixed: CSAT Sochor was not firing.

**Comment by Freddo3000** [comment]
Updated in release branch
