### ISSUE TITLE
CBA settings function gets called despite CBA not being active, causing issues.

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#76]
https://github.com/genesis92x/VcomAI-3.0/blob/02da0eecb259a2470f64fa4195f144f7deb73e1d/Vcom/VcomInit.sqf#L17

**Comment by NZF-JDWang** [comment]
Notice after updating our current mission to the 3.2 RC that none of the settings in cba_settings.sqf seem to take. Is this the same issue?

**Comment by Freddo3000** [comment]
@NZF-JDWang I am not able to replicate this. Is this on a dedicated server?

**Comment by NZF-JDWang** [comment]
Sorry @Freddo3000, I was using an old description.ext and that seemed to be my problem

**Comment by NZF-JDWang** [comment]
Ok now I'm really confused. 
I downloaded the RC3.2 script and made a test mission using that and the description.ext file that came with it. The following is my cba_setting.sqf
```
// VCOM DRIVING
force VCM_DRIVERLIMIT = 4;
force VCM_DrivingActivated = true;
force VCM_DrivingDelay = 0.75;
force VCM_DrivingDist = 10;

// VCOM SETTINGS
force VCM_ActivateAI = true;
force VCM_ADVANCEDMOVEMENT = true;
force VCM_AIDISTANCEVEHPATH = 0;
force VCM_AIHEALING = true;
force VCM_AIMagLimit = 2;
force VCM_ARTYDELAY = 300;
force VCM_ARTYENABLE = true;
force VCM_ARTYSIDES = [RESISTANCE,EAST];
force VCM_ARTYSPREAD = 400;
force VCM_Debug = false;
force VCM_ForceSpeed = false;
force VCM_FRMCHANGE = true;
force VCM_HEARINGDISTANCE = 800;
force VCM_LGARRISONCHANCE = 29.7459;
force VCM_MINECHANCE = 9.69248;
force VCM_RAGDOLL = false;
force VCM_RAGDOLLCHC = 0;
force VCM_SIDEENABLED = [RESISTANCE,EAST];
force VCM_STATICARMT = 300;
force VCM_StealVeh = false;
force VCM_WARNDELAY = 30;
force VCM_WARNDIST = 1000;

// VCOM SKILL SETTINGS
force VCM_AISKILL_AIMINGACCURACY_E = 0.25;
force VCM_AISKILL_AIMINGACCURACY_R = 0.25;
force VCM_AISKILL_AIMINGACCURACY_W = 0.202763;
force VCM_AISKILL_AIMINGSHAKE_E = 0.15;
force VCM_AISKILL_AIMINGSHAKE_R = 0.15;
force VCM_AISKILL_AIMINGSHAKE_W = 0.15;
force VCM_AISKILL_AIMINGSPEED_E = 0.35;
force VCM_AISKILL_AIMINGSPEED_R = 0.35;
force VCM_AISKILL_AIMINGSPEED_W = 0.35;
force VCM_SIDESPECIFICSKILL = true;
force VCM_SKILLCHANGE = true;
```
 If I then enter the mission, bring up the debug and type 
`VCM_SIDEENABLED` into a watch box, it returns ` [WEST, EAST, GUER]` yet the cba_settings.sqf doesn't include WEST 

If I globally exec `VCM_SIDEENABLED = [RESISTANCE, EAST]` then the watchbox changes as it should to `[GUER,EAST]`

So to me this means it's not reading from the cba_setting.sqf 
I've attached the mission so you can check. I hope I'm not just doing something stupid 


[VCOM_TEST.Malden.zip](https://github.com/genesis92x/VcomAI-3.0/files/2824943/VCOM_TEST.Malden.zip)

**Comment by Freddo3000** [comment]
Fixed in https://github.com/genesis92x/VcomAI-3.0/releases/tag/3.2.1
