### ISSUE TITLE
AI has abnormal low willings to execute "long-range" movement

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#80]
I'm using the script version of the latest pre-release v3.2.1, and I've noticed AI has abnormal low willings to execute "long-range" movement. AI seems to refuse reinforce allies further than 300m although the reinforce distance was set to 2500(max) and wait time set to 15s, and those within 300m seems to use a really low speed to move towards players, which makes AI looks awfully lazy.

This mod does not show enough info in debug mode, so I cannot give more detailed description.

**Comment by GoldJohnKing** [comment]
Well, I use latest release version v3.1 as a comparision, AI can move up to 6km to reinforce.

**Comment by Freddo3000** [comment]
The latest development version has had a new reinforcement system implemented, you should check that out.

**Comment by GoldJohnKing** [comment]
No. I use the default params via CBA Settings provided in v3.2.1, AI do not reinforce.

**Comment by GoldJohnKing** [comment]
Problem solved by the merge of release/3.2.2 branch.
