### ISSUE TITLE
Overhaul AI hearing

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#88]
The hearing system in its current state is not very good, and gives the impression of AI being more or less aimbots with only a couple of shots is enough for them to pinpoint your position.

Instead, it should assign you a very low reveal value (around 0.1 - 0.5) and change units from "SAFE" to "AWARE". This should be enough to make them look towards your position, but not directly engage.

**Comment by Freddo3000** [comment]
Overtuned it in latest release, now AI hardly reacts at all. Will change.

**Comment by genesis92x** [comment]
It was definitely too sensitive before, but I feel like we can optimize it more by just using the reveal value and cut the changing units from SAFE to AWARE, as it can cause further issues with the AI.

**Comment by aussie-battler** [comment]
Great work guys on keeping this up to date, love your work. 

I have found in Ver 3.2.2 that you can kill two ai in a patrol & they are not aware of anything. The patrol will keep walking casually in the SAFE state. Usually when you shoot the third they all start going into the AWARE state.

I have changed the ai hearing to 300m, so I will put it back to default 800m and let you know of any changes.

cheers
