### ISSUE TITLE
Still seeing civilians flock to investigate dead bodies 3.2 release 

### ISSUE THREAD

**Issue by NZF-JDWang** [genesis92x/VcomAI-3.0#91]
https://imgur.com/epjioIw

Using ALiVE (thought this only happens with VCOM active) 
Whenever I shoot an OPFOR a bunch of civilians set waypoints to the dead body 

This was an issue with earlier versions and was fixed but it seems to be back again.
Civilians need to be removed from VCOM, but added for VCOM driving

**Comment by xetra11** [comment]
I kinda like that but yea should be removable if not intended

**Comment by NZF-JDWang** [comment]
It _would_ be cool if it were only close by civilians, and they only stopped for a bit before going about their business, but instead it pulls civs from miles away, sometimes emptying villages just so they can stand around a dead body.

**Comment by Freddo3000** [comment]
Can't replicate on [develop](/genesis92x/VcomAI-3.0/tree/develop) branch
