### ISSUE TITLE
Deprecate AI "skill" settings

### ISSUE THREAD

**Issue by Freddo3000** [genesis92x/VcomAI-3.0#92]
**Is your feature request related to a problem? Please describe.**
Changing AI skill settings, in my opinion, is something that the server settings should be doing through the [server.armaprofile](https://community.bistudio.com/wiki/server.armaprofile) file.

**Describe the solution you'd like**
Disable VCOM AI skill settings by default or remove it.

**Additional context**
This may improve the compatibility between this and [ASR AI](https://forums.bohemia.net/forums/topic/163742-asr-ai-3/) and [CF_BAI](https://github.com/BrightCandle/cf_bai).

**Comment by genesis92x** [comment]
I don't really like just disabling features here and there. I don't mind people being able to disable it, but what's the argument against having mod-side skill settings?
