### ISSUE TITLE
VCOM 3.3.0

### ISSUE THREAD

**Issue by HwBunk** [genesis92x/VcomAI-3.0#94]
While controlling the ai,when you shoot a couple of shoot it will cause the AI to slide to crouch

1.Control AI
2.Shoot a couple of time with sniper or rifle
3.End result it will slide and crouch
Also when you lean and shooting it will still make you crouch

**Expected behavior**
  forced AI to slide to crouch

**Screenshots**
-none

**VCOM Version:**
 - Version [e.g. 3.3.0]
 
**Additional mods used:**
 - e.g CBA_A3 (v3.10.1.190316)
 -RHSUSAF,RHSAFRF,RHSGREF....

**Additional context**
-none

**Comment by Freddo3000** [comment]
Will fix in the next release, which will hopefully be soon.

**Comment by Quailsnap** [comment]
Looking forward to it. Breaking Zeus for me, right now, and I've torn VCOM out of our server until it's fixed.
