### ISSUE TITLE
AI Point Blank Combat and other stuff

### ISSUE THREAD

**Issue by HwBunk** [genesis92x/VcomAI-3.0#97]
**Is your feature request related to a problem? Please describe.**
Yes,When at a close range combat the AI won't spam their pistol they slowly shoot it like there is time to live even though there is 2 enemy AI .They keep on (sometime) runaway while underfire at close range combat.The sniper AI with bolt action rifle keep on shoot it to early and misses shot even though the skill is high.AI don't change the rifle to burst or auto at close range.

**Describe the solution you'd like**
When at close range full on auto fire on the enemy.Make AI sniper skill at 100% shoot accurately at close.At close range,pistol shoot quicker and accurate.AI can change rifle firing mode.

**Comment by Freddo3000** [comment]
Firing mode on pistols is a config issue, not something we should fix with scripts. Ask the mod developers to fix it, or make a replacement config.

AI firing too early is not something we can fix either unfortunately.

**Comment by genesis92x** [comment]
Freddo is right about the firing modes for AI. It's a config issue that scripts can't touch.

Changing AI skill based on distance has been something I have looked at before. While it sounds good in theory, I haven't been able to create a system that worked well. It just made CQC a nightmare, and made the AI feel more "hacky" than anything else.

Something you can try, is to increase the skill level of the AI on your game, as well as in the config file for Vcom AI.
