### ISSUE TITLE
[Possible Bug]AI infantry won't fall on formation while in non-combat mode without waypoint.

### ISSUE THREAD

**Issue by GoldJohnKing** [genesis92x/VcomAI-3.0#98]
**Describe the bug**
- AI infantry won't fall on any formation while in non-combat mode without waypoint. 
- Some of those AI are just spawned in a random formation and they do not change formation based on terrain, some has just finished their reinforcement and remain their position like that. This made AI more crowded than before. 
- According to changelog [3.2] - 2019-01-20, AI should prefer forming convoys/columns, but I'm not sure if there's a logic handling them without waypoints, so I wonder if this is a bug. Besides, vanilla AI would auto fall on formation even they are in non-combat mode without waypoint.

**To Reproduce**
1. Go to see some mission spawned or reinforcement-finished AI and you will notice this.

**Expected behavior**
AI should auto change their formation based on terrain in safe mode, and they shall keep a safe distance between each other.

**Screenshots**
Please notice that all AI in each picture belongs to the same group.
![107410_20190330003907_1](https://user-images.githubusercontent.com/26923626/55249036-1d2b8f00-5286-11e9-87e3-6e971e035215.png)
![107410_20190330003914_1](https://user-images.githubusercontent.com/26923626/55249037-1dc42580-5286-11e9-9929-93097ec193ba.png)
![107410_20190330003945_1](https://user-images.githubusercontent.com/26923626/55249038-1e5cbc00-5286-11e9-9147-72431cde796e.png)

**VCOM Version:**
 - Branch: [Master]
 - Version [3.3.0]

**Comment by Freddo3000** [comment]
Are they in "SAFE" [behaviour](https://community.bistudio.com/wiki/behaviour)?

**Comment by GoldJohnKing** [comment]
Both SAFE or AWARE has been seen, not sure about COMBAT or STEALTH. 
However, according to this (https://github.com/genesis92x/VcomAI-3.0/issues/96), even some of those AI in combat mode has low willing to "move", so I wonder if this is a separated bug.

**Comment by genesis92x** [comment]
Interesting behavior. It would be expected that they get back into formation after completing their waypoint.

**Comment by GoldJohnKing** [comment]
They did not even move a bit if they are not assigned a waypoint. This also happens when they finished their waypoints. They just stay where they are upon spawned or after finished reinforcement. Dragging them anywhere wont drive them move. 😭
