### ISSUE TITLE
Steal vehicles function removed?

### ISSUE THREAD

**Issue by serialtasted** [genesis92x/VcomAI-3.0#99]
In latest verion (3.3.0) I'm trying to find in the source code the function for the vehicle stealing part. But I only manage to find  the variable that defines if it's enable or not.

Have I missed something here?

**Comment by genesis92x** [comment]
It looks like this code was removed. Good catch. This is a function I really liked myself - however I would like to rework it for more complexity.

Perhaps:
All AI can steal wheeled vehicles
Crewmen can steal wheeled vehicles & armored vehicles
Pilots can steal helicraft/planes
?

**Comment by serialtasted** [comment]
I think Ai being able to steal air vehicle would be a bit off. But for land vehicles that's a good idea, normal AI only being able to steal simpler vehicles and crewman being able to steal those simpler vehicles + armored.

I detected this portion of code was missing because I always change it one more condition to be able to fine tune which groups are allowed to steal vehicles and what not. Without the need to lock and unlock vehicles because sometimes I want for example enemy insurgent groups being able to steal my vehicles but friendly don't and only use them if ordered to. Having to lock and unlock vehicles and validate this would be just crazy and would take so much performance

**Comment by Freddo3000** [comment]
I was going to rework it as to #87, but the update was pushed before I made any progress on it.

**Comment by genesis92x** [comment]
@Freddo3000 You had three months! THREE MONTHS! COME ON!!!! :D 

That's something that I would like to do, I will take care of that
